### ISSUE TITLE
DID token validation causes NameError

### ISSUE THREAD

**Issue by spidzio** [magiclabs/magic-admin-ruby#11]
### ✅ Prerequisites

- [ v ] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [ v ] Are you running the latest SDK version?
- [ v ] Are you reporting to the correct repository (`magic-admin-ruby`)?

### 🐛 Description

Reference to the `Eth` gem causes `NameError` on `Eth::Utils` call. The name has been changed to `Eth::Util` in the `Eth 0.5`

### 🧩 Steps to Reproduce

It happens on the DID token validation

### 🤔 Expected behavior

Not to get the `NameError`

### 😮 Actual behavior

```
.../gems/ruby-3.1.1/gems/magic-admin-0.1.2/lib/magic-admin/resource/token.rb:104:in `rec_pub_address': uninitialized constant Eth::Utils (NameError)
                                            
        Eth::Utils.public_key_to_address personal_recover(claim, proof)
           ^^^^^^^                                                        
```

### 💻 Code Sample

```ruby
# Gemfile

gem 'magic-admin'


# Code that causes error

magic = Magic.new(api_secret_key: 'secret key')
did_token = 'the DID token from Authorization header'
magic.token.validate(did_token)
```

### 🌎 Environment

| Software            | Version(s) |
| --------------------- | ---------- |
| `magic-admin-ruby`  |      0.1.2     |
| `ruby`                          |      3.1.1      |
| `rails`   |   7.0.2.23 |
| `bundler` | 2.3.7 | 
| Operating System    |            |

**Comment by barabasicsongor** [comment]
Hey Magic team, do you have any updates on this?

**Comment by q9f** [comment]
I proposed a fix in #12

**Comment by spidzio** [comment]
Tiny little fixes. Ship it.

**Comment by spidzio** [comment]
@smithki when will you release the new gem version with these changes?
