### ISSUE TITLE
User actions fail if Etc.getlogin() returns nil

### ISSUE THREAD

**Issue by patrickfrancis** [magiclabs/magic-admin-ruby#5]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-admin-ruby`)?

### 🐛 Description

In config.rb, the [user_name](https://github.com/magiclabs/magic-admin-ruby/blob/c22a48cf651fa343bd01da18c3017b7d5cf51389/lib/magic-admin/config.rb#L40) function has no error checking on the result of Etc.getlogin(). ﻿If Etc.getlogin() returns nil, the function throws an exception, which prevents any of the user.get_metadata_by_* functions from succeeding.

### 🧩 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### 🤔 Expected behavior

[What you expected to happen?]

### 😮 Actual behavior
```
irb(main):006:0> resp = magic.user.get_metadata_by_token(token)
Traceback (most recent call last):
       16: from railties (5.2.4.4) lib/rails/command.rb:46:in `invoke'
       15: from railties (5.2.4.4) lib/rails/command/base.rb:69:in `perform'
       14: from thor (0.20.3) lib/thor.rb:387:in `dispatch'
       13: from thor (0.20.3) lib/thor/invocation.rb:126:in `invoke_command'
       12: from thor (0.20.3) lib/thor/command.rb:27:in `run'
       11: from railties (5.2.4.4) lib/rails/commands/console/console_command.rb:96:in `perform'
       10: from railties (5.2.4.4) lib/rails/commands/console/console_command.rb:19:in `start'
        9: from railties (5.2.4.4) lib/rails/commands/console/console_command.rb:64:in `start'
        8: from (irb):6
        7: from magic-admin (0.1.1) lib/magic-admin/resource/user.rb:73:in `get_metadata_by_token'
        6: from magic-admin (0.1.1) lib/magic-admin/resource/user.rb:41:in `get_metadata_by_issuer'
        5: from magic-admin (0.1.1) lib/magic-admin/util.rb:56:in `headers'
        4: from magic-admin (0.1.1) lib/magic-admin/util.rb:37:in `user_agent'
        3: from magic-admin (0.1.1) lib/magic-admin/util.rb:21:in `platform_info'
        2: from magic-admin (0.1.1) lib/magic-admin/config.rb:40:in `user_name'
        1: from magic-admin (0.1.1) lib/magic-admin/config.rb:40:in `getpwnam'
TypeError (no implicit conversion of nil into String)
```

### 💻 Code Sample

[If possible, please provide a code repository, gist, code snippet or sample files to reproduce the issue.]

### 🌎 Environment

| Software            | Version(s) |
| ------------------- | ---------- |
| `magic-admin-ruby`  |            |
| `ruby`              |            |
| Operating System    |            |

**Comment by FYJen** [comment]
@patrickfrancis: Thank you for reporting this issue. We've just released a patch to fix the issue in `0.1.2` :).
