### ISSUE TITLE
installed gem causes rails to hang, possible segfault?

### ISSUE THREAD

**Issue by jeffrwells** [magiclabs/magic-admin-ruby#7]
I installed Magic yesterday but the ruby gem causes Rails to hang.

When running `rails c` the process hangs, with no error or output until killed.

gem 0.1.2
ruby 2.6.5p114
Rails 5.2.4.4

It appears to segfault when loading it's dependency `eth`, which loads `money-tree`, which dies on this line: [https://github.com/GemHQ/money-tree/blob/master/lib/openssl_extensions.rb#L9](https://github.com/GemHQ/money-tree/blob/master/lib/openssl_extensions.rb#L9)

This might be related to this issue: [https://github.com/ffi/ffi/issues/634](https://github.com/ffi/ffi/issues/634) . My guess is it's caused by the ruby version.

I downloaded this gem and tried to load the lib files, and got an `Abort` in the terminal. I did this for each gem until I found the culprit line.

**Comment by slicksammy** [comment]
I'm having a similar issue:
`/Users/sammy/.rvm/rubies/ruby-2.7.0/bin/ruby is loading libcrypto in an unsafe way`
I can tell this is because of `magic-admin` gem because when I remove it from my Gemfile I don't see the issue anymore

I'm using
gem 0.1.2
ruby 2.7.0p0
rails 6.1.0

**Comment by NikolayRys** [comment]
I have this issue too. 
I've done some investigation, it seems to come from the "eth" gem: https://github.com/magiclabs/magic-admin-ruby/blob/master/lib/magic-admin.rb#L9 .  It uses "money-tree" gem: https://github.com/se3000/ruby-eth/blob/develop/lib/eth.rb#L3 , which has been unmaintained for a long time.
Here is the offending line: https://github.com/GemHQ/money-tree/blob/master/lib/openssl_extensions.rb#L9

Which can be tried separately:
```
require 'ffi'
module OpenSSLExtensions
  extend FFI::Library
  ffi_lib ['ssl']
end
```
This produces the exact same error for me, as for @slicksammy. 

So, the question to the maintainer is, why does this lib need dependencies for mining cryptocurrency?

**Comment by NikolayRys** [comment]
Here's the solution, please see the comment by @fero46:
https://github.com/GemHQ/money-tree/issues/38

**Comment by glitch003** [comment]
Same issue here, and the solution provided by @NikolayRys worked for me on macos 10.15.7.  Thanks @NikolayRys !!
